# Generated by Django 5.1.5 on 2025-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_medicine_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
