# Generated by Django 5.1.5 on 2025-01-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='discount',
        ),
    ]
