# Generated by Django 5.1.5 on 2025-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_medicine_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
