# Generated by Django 5.1.5 on 2025-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_medicine_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('posting', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('department_contact_number', models.CharField(max_length=15)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
