# Generated by Django 5.1.5 on 2025-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_medicalprofessional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalProfessional',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.CharField(default='Generic', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Gynecology', 'Gynecology'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
