# Generated by Django 5.1.5 on 2025-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_medicalprofessional_remove_medicine_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='code',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
