# Generated by Django 5.1.5 on 2025-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_department_medicine_code_alter_medicine_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
