# Generated by Django 5.1.5 on 2025-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_billing_patientrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientQuery',
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
