# Generated by Django 5.1.5 on 2025-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_patientquery_delete_patientrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='created_at',
            new_name='invoice_date',
        ),
        migrations.AddField(
            model_name='billing',
            name='diagnosis',
            field=models.CharField(default='Unknown Diagnosis', max_length=255),
            preserve_default=False,
        ),
    ]
