# Generated by Django 5.1.5 on 2025-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
