# Generated by Django 5.1.5 on 2025-04-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cpt_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='icd10_code',
        ),
    ]
