# Generated by Django 5.1.5 on 2025-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_invoice_appointment_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
