# Generated by Django 5.1.5 on 2025-04-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='file',
        ),
    ]
