# Generated by Django 5.1.5 on 2026-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
