# Generated by Django 5.1.5 on 2026-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_doctor_fee_roomallotment_room_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
