# Generated by Django 5.1.5 on 2026-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_patient_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Checked', 'Checked'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Waiting', max_length=20),
        ),
    ]
