# Generated by Django 5.1.5 on 2026-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
